name: 'Build container: fcos-server'

env:
  IMAGE_NAME: fcos-server

on:
  workflow_run:
    workflows: ['Build container: fcos-zfs']
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - server.dockerfile
      - .github/workflows/build-fcos-base.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: server.dockerfile
          image: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          layers: false
          oci: true

      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          registry: ghcr.io
          tags: latest
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify failed build
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: '@everyone FCOS **Server** build has **failed**'
          embed-title: 'Finished workflow with errors'
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-timestamp: ${{ github.event.repository.updated_at }}
          embed-color: 16734296

      - name: Notify successfull build
        if: success()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: '@everyone FCOS **Server** build was **successfull**'
          embed-title: 'Finished workflow without errors'
          embed-url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-timestamp: ${{ github.event.repository.updated_at }}
          embed-color: 5832553